/**
 * Bitcoind
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.BIPReject;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BIP {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("version")
  private Integer version = null;
  @SerializedName("reject")
  private BIPReject reject = null;

  /**
   * The BIP number, or ? before being assigned
   **/
  @ApiModelProperty(value = "The BIP number, or ? before being assigned")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * The BIP version number
   **/
  @ApiModelProperty(value = "The BIP version number")
  public Integer getVersion() {
    return version;
  }
  public void setVersion(Integer version) {
    this.version = version;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BIPReject getReject() {
    return reject;
  }
  public void setReject(BIPReject reject) {
    this.reject = reject;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BIP BIP = (BIP) o;
    return (this.id == null ? BIP.id == null : this.id.equals(BIP.id)) &&
        (this.version == null ? BIP.version == null : this.version.equals(BIP.version)) &&
        (this.reject == null ? BIP.reject == null : this.reject.equals(BIP.reject));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.version == null ? 0: this.version.hashCode());
    result = 31 * result + (this.reject == null ? 0: this.reject.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BIP {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  version: ").append(version).append("\n");
    sb.append("  reject: ").append(reject).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
