/**
 * Bitcoind
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.BIP9;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * status of BIP9 softforks in progress
 **/
@ApiModel(description = "status of BIP9 softforks in progress")
public class ChainInfoBip9Softforks {
  
  @SerializedName("name")
  private BIP9 name = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public BIP9 getName() {
    return name;
  }
  public void setName(BIP9 name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChainInfoBip9Softforks chainInfoBip9Softforks = (ChainInfoBip9Softforks) o;
    return (this.name == null ? chainInfoBip9Softforks.name == null : this.name.equals(chainInfoBip9Softforks.name));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChainInfoBip9Softforks {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
