/**
 * Bitcoind
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.UTxO;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse200 {
  
  @SerializedName("chainHeight")
  private Integer chainHeight = null;
  @SerializedName("chaintipHash")
  private String chaintipHash = null;
  @SerializedName("bitmap")
  private String bitmap = null;
  @SerializedName("utxos")
  private List<UTxO> utxos = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getChainHeight() {
    return chainHeight;
  }
  public void setChainHeight(Integer chainHeight) {
    this.chainHeight = chainHeight;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getChaintipHash() {
    return chaintipHash;
  }
  public void setChaintipHash(String chaintipHash) {
    this.chaintipHash = chaintipHash;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBitmap() {
    return bitmap;
  }
  public void setBitmap(String bitmap) {
    this.bitmap = bitmap;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<UTxO> getUtxos() {
    return utxos;
  }
  public void setUtxos(List<UTxO> utxos) {
    this.utxos = utxos;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return (this.chainHeight == null ? inlineResponse200.chainHeight == null : this.chainHeight.equals(inlineResponse200.chainHeight)) &&
        (this.chaintipHash == null ? inlineResponse200.chaintipHash == null : this.chaintipHash.equals(inlineResponse200.chaintipHash)) &&
        (this.bitmap == null ? inlineResponse200.bitmap == null : this.bitmap.equals(inlineResponse200.bitmap)) &&
        (this.utxos == null ? inlineResponse200.utxos == null : this.utxos.equals(inlineResponse200.utxos));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.chainHeight == null ? 0: this.chainHeight.hashCode());
    result = 31 * result + (this.chaintipHash == null ? 0: this.chaintipHash.hashCode());
    result = 31 * result + (this.bitmap == null ? 0: this.bitmap.hashCode());
    result = 31 * result + (this.utxos == null ? 0: this.utxos.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("  chainHeight: ").append(chainHeight).append("\n");
    sb.append("  chaintipHash: ").append(chaintipHash).append("\n");
    sb.append("  bitmap: ").append(bitmap).append("\n");
    sb.append("  utxos: ").append(utxos).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
