/**
 * Bitcoind
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ScriptPubKey {
  
  @SerializedName("asm")
  private String asm = null;
  @SerializedName("hex")
  private String hex = null;
  @SerializedName("reqSigs")
  private Integer reqSigs = null;
  public enum TypeEnum {
     nonstandard,  pubkey,  pubkeyhash,  scripthash,  multisig,  nulldata,  witness_v0_keyhash,  witness_v0_scripthash,  witness_unknown, 
  };
  @SerializedName("type")
  private TypeEnum type = null;
  @SerializedName("addresses")
  private List<String> addresses = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAsm() {
    return asm;
  }
  public void setAsm(String asm) {
    this.asm = asm;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHex() {
    return hex;
  }
  public void setHex(String hex) {
    this.hex = hex;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getReqSigs() {
    return reqSigs;
  }
  public void setReqSigs(Integer reqSigs) {
    this.reqSigs = reqSigs;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }
  public void setType(TypeEnum type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getAddresses() {
    return addresses;
  }
  public void setAddresses(List<String> addresses) {
    this.addresses = addresses;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScriptPubKey scriptPubKey = (ScriptPubKey) o;
    return (this.asm == null ? scriptPubKey.asm == null : this.asm.equals(scriptPubKey.asm)) &&
        (this.hex == null ? scriptPubKey.hex == null : this.hex.equals(scriptPubKey.hex)) &&
        (this.reqSigs == null ? scriptPubKey.reqSigs == null : this.reqSigs.equals(scriptPubKey.reqSigs)) &&
        (this.type == null ? scriptPubKey.type == null : this.type.equals(scriptPubKey.type)) &&
        (this.addresses == null ? scriptPubKey.addresses == null : this.addresses.equals(scriptPubKey.addresses));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.asm == null ? 0: this.asm.hashCode());
    result = 31 * result + (this.hex == null ? 0: this.hex.hashCode());
    result = 31 * result + (this.reqSigs == null ? 0: this.reqSigs.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.addresses == null ? 0: this.addresses.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScriptPubKey {\n");
    
    sb.append("  asm: ").append(asm).append("\n");
    sb.append("  hex: ").append(hex).append("\n");
    sb.append("  reqSigs: ").append(reqSigs).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  addresses: ").append(addresses).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
