/**
 * Bitcoind
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.ScriptPubKey;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UTxO {
  
  @SerializedName("txvers")
  private Integer txvers = null;
  @SerializedName("height")
  private Integer height = null;
  @SerializedName("value")
  private Float value = null;
  @SerializedName("scriptPubKey")
  private ScriptPubKey scriptPubKey = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTxvers() {
    return txvers;
  }
  public void setTxvers(Integer txvers) {
    this.txvers = txvers;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getHeight() {
    return height;
  }
  public void setHeight(Integer height) {
    this.height = height;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Float getValue() {
    return value;
  }
  public void setValue(Float value) {
    this.value = value;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ScriptPubKey getScriptPubKey() {
    return scriptPubKey;
  }
  public void setScriptPubKey(ScriptPubKey scriptPubKey) {
    this.scriptPubKey = scriptPubKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UTxO uTxO = (UTxO) o;
    return (this.txvers == null ? uTxO.txvers == null : this.txvers.equals(uTxO.txvers)) &&
        (this.height == null ? uTxO.height == null : this.height.equals(uTxO.height)) &&
        (this.value == null ? uTxO.value == null : this.value.equals(uTxO.value)) &&
        (this.scriptPubKey == null ? uTxO.scriptPubKey == null : this.scriptPubKey.equals(uTxO.scriptPubKey));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.txvers == null ? 0: this.txvers.hashCode());
    result = 31 * result + (this.height == null ? 0: this.height.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    result = 31 * result + (this.scriptPubKey == null ? 0: this.scriptPubKey.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UTxO {\n");
    
    sb.append("  txvers: ").append(txvers).append("\n");
    sb.append("  height: ").append(height).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("  scriptPubKey: ").append(scriptPubKey).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
